package com.codeway.guessinggame.ui;

import java.awt.Image;
import javax.swing.ImageIcon;

public class GameOverUi extends javax.swing.JFrame {

  /**
   * Creates new form GameOverUi
   */
  String name;
  public GameOverUi( String name) {
    this.name = name;

    initComponents();
    ScaleImage();
  }

  public void ScaleImage() {
    ImageIcon icon = new ImageIcon(
      "src\\com\\codeway\\guessinggame\\ui\\assets\\gameover.jpg"
    );
    Image img = icon.getImage();
    Image imgScale = img.getScaledInstance(
      label.getWidth(),
      label.getHeight(),
      Image.SCALE_SMOOTH
    );
    ImageIcon scaledIcon = new ImageIcon(imgScale);
    label.setIcon(scaledIcon);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

  private void initComponents() {
    label = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jButton1.setBackground(new java.awt.Color(51, 255, 51));
    jButton1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
    jButton1.setForeground(new java.awt.Color(0, 0, 255));
    jButton1.setText("Try Again");
    jButton1.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton1ActionPerformed(evt);
        }
      }
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(
              label,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
            .addContainerGap()
        )
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(130, 130, 130)
            .addComponent(
              jButton1,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              160,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addContainerGap(136, Short.MAX_VALUE)
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(
              label,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              282,
              Short.MAX_VALUE
            )
            .addGap(18, 18, 18)
            .addComponent(
              jButton1,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              70,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
        )
    );

    pack();
    setLocationRelativeTo(null);
  } // </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:

    new MainGameUi(name).setVisible(true);
    this.dispose();
  } //GEN-LAST:event_jButton1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger
        .getLogger(GameOverUi.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger
        .getLogger(GameOverUi.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger
        .getLogger(GameOverUi.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger
        .getLogger(GameOverUi.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
      new Runnable() {
        public void run() {
          new GameOverUi("").setVisible(true);
        }
      }
    );
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel label;
  // End of variables declaration//GEN-END:variables
}
